development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: votmekeskus_development
  pool: 5
  username: administrator
  password:
  template: template0

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: votmekeskus_test
  pool: 5
  username: administrator
  password:
  template: template0

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: votmekeskus_production
  pool: 5
  username: votmekeskus
  password: <%= ENV['VOTMEKESKUS_DATABASE_PASSWORD'] %>
  template: template0
